draw_config:
  key_w: 60
  key_h: 56
  inner_pad_w: 6
  inner_pad_h: 6
  n_columns: 1

parse_config:
  raw_binding_map:
    "&to 0":           {t: "△"}
    "&mmv MOVE_UP":    {t: "$$material:arrow_upward$$",   h: "$$material:mouse$$"}
    "&mmv MOVE_DOWN":  {t: "$$material:arrow_downward$$", h: "$$material:mouse$$"}
    "&mmv MOVE_RIGHT": {t: "$$material:arrow_forward$$",  h: "$$material:mouse$$"}
    "&mmv MOVE_LEFT":  {t: "$$material:arrow_back$$",     h: "$$material:mouse$$"}
    "&mkp LCLK":       {t: "$$material:left_click$$"}
    "&mkp RCLK":       {t: "$$material:right_click$$"}
    "&mkp MCLK":       {t: "$$material:drag_pan$$"}
